[package]
name = "simple_http"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6.1.0"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
simple_logger = "5.0.0"
toml = "0.8.22"
